/random/setSeeds 12345 67890
/sim/particle proton
/sim/sensitiveXY 20 um
/sim/deadXY 20 um
/sim/sensitiveThickness 5 um
/sim/deadThickness 1 um
/sim/sensitiveMaterial GaAs
/sim/deadMaterial Al2O3
/sim/biasCrossSectionFactor 1041
/sim/useCollectionModel true
/sim/carrierLifetime 1.0 ns
/sim/electricField 1000000 volt/m
/run/initialize
/run/reinitializeGeometry

/sim/energy 50 MeV
/sim/beamXY 20 um
/sim/criticalCharge 150
/sim/verbose false

/run/beamOn 1000000
