/random/setSeeds 12345 67890
/sim/particle proton
/sim/sensitiveXY .25 um
/sim/deadXY .25 um
/sim/sensitiveThickness .5 um
/sim/deadThickness 5 um
/sim/incidentAngle 0 deg
/sim/sensitiveMaterial Si
/sim/deadMaterial SiO2
/sim/biasCrossSectionFactor 1041
/sim/useCollectionModel true
/sim/carrierLifetime 1.0 ns
/sim/electricField 1000000 volt/m
/run/initialize
/run/reinitializeGeometry

/sim/energy 200 MeV
/sim/beamXY .25 um
/sim/criticalCharge 150
/sim/verbose false
/sim/logRecoilHits true

/vis/open OGLSX
/vis/viewer/set/viewpointVector 1 0 0
/vis/drawVolume
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 100
/vis/multithreading/actionOnEventQueueFull discard
/vis/viewer/flush

/run/beamOn 1000000
