/random/setSeeds 77733 77744
/sim/particle triton
/sim/sensitiveXY 10 um
/sim/deadXY 10 um
/sim/sensitiveThickness 8 um
/sim/deadThickness 5 um
/sim/useCollectionModel true
/sim/biasCrossSectionFactor 1
/sim/carrierLifetime 1.0 ns
/sim/electricField 1000000 volt/m
/run/initialize
/run/reinitializeGeometry

/sim/energy 200 MeV
/sim/beamXY 10 um
/sim/criticalCharge 150
/sim/verbose false
/run/beamOn 10000000
